### ISSUE TITLE
mDNS setup

### ISSUE THREAD

**Issue by Syndesi** [ember-nexus/development-setup#1]
Investigate whether the locally running Traefik instance can serve websites to other devices in the local network through mDNS.
First unsuccessful example included:

```yml
  ember-nexus-proxy-avahi-cname:
    container_name: ember-nexus-proxy-avahi-cname
    network_mode: host
    volumes:
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
    image: "ghcr.io/grishy/go-avahi-cname:v2.0.6"
    command:
      - cname
      - api
      - neo4j
      - kibana
      - redisinsight
      - rabbitmq
      - minio
      - proxy
      - logs
      - index
```

And debugging commands:

```bash
sudo nbtscan -r 192.168.188.0/24
avahi-browse -a
sudo ss -tunlp | grep 5353
```
